package com.example.quote.viewModel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.quote.FavoritesRepository
import com.example.quote.QuoteRepository
import com.example.quote.data.SupabaseClient
import com.example.quote.model.Favorite
import com.example.quote.model.Quote
import io.github.jan.supabase.auth.auth
import kotlinx.coroutines.launch

class QuoteViewModel : ViewModel() {

    private val quoteRepository = QuoteRepository()
    private val favoritesRepository = FavoritesRepository()

    var quotes by mutableStateOf<List<Quote>>(emptyList())
        private set

    var loading by mutableStateOf(false)
        private set

    // Stores the IDs of quotes the user has liked
    var favoriteIds = mutableStateListOf<String>()
        private set

    private fun getCurrentUserId(): String {
        return SupabaseClient.client.auth.currentUserOrNull()?.id ?: ""
    }

    fun fetchQuotes() {
        viewModelScope.launch {
            loading = true
            try {
                quotes = quoteRepository.getQuotes()
                loadFavorites()
            } catch (e: Exception) {
                e.printStackTrace()
            } finally {
                loading = false
            }
        }
    }

    fun toggleFavorite(quote: Quote) {
        val userId = getCurrentUserId()
        if (userId.isEmpty()) return

        viewModelScope.launch {
            if (favoriteIds.contains(quote.id)) {
                // 1. Remove from local list immediately (UI updates fast)
                favoriteIds.remove(quote.id)

                // 2. Remove from Database
                try {
                    favoritesRepository.removeFavorite(quote.id, userId)
                } catch (e: Exception) {
                    // Revert if it fails
                    favoriteIds.add(quote.id)
                }
            } else {
                // 1. Add to local list immediately
                favoriteIds.add(quote.id)

                // 2. Add to Database
                try {
                    // UPDATED HERE: Matches your specific Favorite data class
                    val favorite = Favorite(
                        user_id = userId,
                        quote_id = quote.id
                        // id is generated by Supabase, so we don't pass it
                    )
                    favoritesRepository.addFavorite(favorite)
                } catch (e: Exception) {
                    // Revert if it fails
                    favoriteIds.remove(quote.id)
                }
            }
        }
    }

    private fun loadFavorites() {
        val userId = getCurrentUserId()
        if (userId.isEmpty()) return

        viewModelScope.launch {
            try {
                val favorites = favoritesRepository.getFavorites(userId)
                favoriteIds.clear()
                // UPDATED HERE: Using 'quote_id' from your data class
                favoriteIds.addAll(favorites.map { it.quote_id })
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }
}